# Generated by Django 3.0.4 on 2020-03-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_name', models.CharField(max_length=200)),
                ('added_email', models.CharField(max_length=200)),
                ('added_phone', models.CharField(max_length=200)),
                ('added_msg', models.CharField(max_length=200)),
            ],
        ),
    ]
